In [2]:
import pandas as pd
from sklearn.naive_bayes import CategoricalNB
x=pd.DataFrame({
    'Outlook': ['Sunny','Sunny','Overcast','Rainy','Rainy','Sunny'],
    'Humidity': ['High','High','High','Normal','Normal','Normal'],
    'Wind': ['Weak','Strong','Weak','Weak','Strong','Weak']})
y=['No','No','Yes','Yes','No','Yes']
x_encoded1=x.apply(lambda col: col.astype('category').cat.codes)
model=CategoricalNB()
model.fit(x_encoded1,y)
test=pd.DataFrame([['Sunny','High','Weak']], columns=x.columns)
test_encoded = test.apply(lambda col: col.astype('category').cat.codes)
print(model.predict(test_encoded))

['No']


In [4]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd
from sklearn.naive_bayes import CategoricalNB
import numpy as np

encoder=OrdinalEncoder()
x_encoded2=encoder.fit_transform(x)
model=CategoricalNB()
model.fit(x_encoded1,y)
test=pd.DataFrame([['Sunny','High','Weak']],columns=x.columns)
test_encoded=test.apply(lambda col:col.astype('category').cat.codes)
print(model.predict(test_encoded))
# Predict using the model
y_pred=model.predict(x_encoded2)
print("\nPredicted values:",y_pred)
# Predict for a new value
new_x=pd.DataFrame([['Rainy','Normal','Strong']],columns=x.columns)
x_encoded = new_x.apply(lambda col:col.astype('category').cat.codes)
new_y = model.predict(x_encoded)
print(f"\nPrediction for x = ['Rainy','Normal','Strong']: y = {new_y[0]}")


['No']

Predicted values: ['No' 'No' 'Yes' 'Yes' 'No' 'Yes']

Prediction for x = ['Rainy','Normal','Strong']: y = No


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(


In [7]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
x=pd.DataFrame({'Color':['Red','Blue','Green','Blue','Red'],
                'Size':['Small','Medium','Large','Small','Large']})
y=['Yes','No','Yes','No','Yes']
encoder=OrdinalEncoder()
x_encoded=encoder.fit_transform(x)
print("Encoded Training Data:",x_encoded)
x_test=pd.DataFrame({'Color':['Green','Red'],'Size':['Medium','Small']})
x_test_encoded=encoder.transform(x_test)
print("Encoded Test Data:",x_test_encoded)


Encoded Training Data: [[2. 2.]
 [0. 1.]
 [1. 0.]
 [0. 2.]
 [2. 0.]]
Encoded Test Data: [[1. 1.]
 [2. 2.]]


In [9]:
#Rest of the code same as previous example
# Test with an unseen category
x_test_new=pd.DataFrame({
'Color': ['Yellow'], # unseen
'Size': ['Small']
})
# Encoder with unknown_value
encoder=OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
encoder.fit(x)
x_test_new_encoded=encoder.transform(x_test_new)
print(x_test_new_encoded)

[[-1.  2.]]


In [10]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
data = {
'Age': [25, 40, 35, 50, 28],
'Income': [50000, 60000, 58000, 80000, 52000],
'MaritalStatus': ['Single', 'Married', 'Single', 'Married', 'Single'],
'CreditScore': [700, 650, 720, 600, 690],
'LoanApproved': ['Yes', 'No', 'Yes', 'No', 'Yes']
}
df = pd.DataFrame(data)
print(df)
X = df.drop('LoanApproved', axis=1)
y = df['LoanApproved']

# Only encode categorical columns
categorical_cols = ['MaritalStatus']
encoder = OrdinalEncoder()
X[categorical_cols] = encoder.fit_transform(X[categorical_cols])
print(X)
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X, y)
# Test example
test = pd.DataFrame({
'Age': [30],
'Income': [54000],
'MaritalStatus': ['Single'],
'CreditScore': [710]
})
# Encode categorical feature
test[categorical_cols] = encoder.transform(test[categorical_cols])
pred = model.predict(test)
print("Predicted Loan Approval:", pred[0])

   Age  Income MaritalStatus  CreditScore LoanApproved
0   25   50000        Single          700          Yes
1   40   60000       Married          650           No
2   35   58000        Single          720          Yes
3   50   80000       Married          600           No
4   28   52000        Single          690          Yes
   Age  Income  MaritalStatus  CreditScore
0   25   50000            1.0          700
1   40   60000            0.0          650
2   35   58000            1.0          720
3   50   80000            0.0          600
4   28   52000            1.0          690
Predicted Loan Approval: Yes


In [15]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
df=pd.read_csv("adult.csv",on_bad_lines='skip')
df=df.replace("",pd.NA)
df=df.dropna()
X=df.drop("income",axis=1)
y=df["income"]
categorical_cols=X.select_dtypes(include="object").columns
encoder=OrdinalEncoder()
X[categorical_cols]=encoder.fit_transform(X[categorical_cols])
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
model=GaussianNB()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred))
print("Classification Report:")
print(classification_report(y_test,y_pred))


Accuracy: 0.7945647167204053
Confusion Matrix:
[[4716  260]
 [1078  459]]
Classification Report:
              precision    recall  f1-score   support

       <=50K       0.81      0.95      0.88      4976
        >50K       0.64      0.30      0.41      1537

    accuracy                           0.79      6513
   macro avg       0.73      0.62      0.64      6513
weighted avg       0.77      0.79      0.77      6513



In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

df=pd.read_csv("adult.csv",on_bad_lines='skip')
df=df.replace("",pd.NA)
df=df.dropna()

X=df.drop("income",axis=1)
y=df["income"]

cat_cols=X.select_dtypes(include="object").columns
encoder=OrdinalEncoder()
X[cat_cols]=encoder.fit_transform(X[cat_cols])

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model=GaussianNB()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

print("Accuracy:",accuracy_score(y_test,y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred))
print("Classification Report:")
print(classification_report(y_test,y_pred))


Accuracy: 0.7945647167204053
Confusion Matrix:
[[4716  260]
 [1078  459]]
Classification Report:
              precision    recall  f1-score   support

       <=50K       0.81      0.95      0.88      4976
        >50K       0.64      0.30      0.41      1537

    accuracy                           0.79      6513
   macro avg       0.73      0.62      0.64      6513
weighted avg       0.77      0.79      0.77      6513



In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

df=pd.read_csv("diabetes.csv")

X=df.drop("Outcome",axis=1)
y=df["Outcome"]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model=GaussianNB()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

print("Accuracy:",accuracy_score(y_test,y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred))
print("Classification Report:")
print(classification_report(y_test,y_pred))


Accuracy: 0.7662337662337663
Confusion Matrix:
[[79 20]
 [16 39]]
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.80      0.81        99
           1       0.66      0.71      0.68        55

    accuracy                           0.77       154
   macro avg       0.75      0.75      0.75       154
weighted avg       0.77      0.77      0.77       154

